services:
  # Backend API Service
  - type: web
    name: kuroai-api
    env: docker
    region: frankfurt  # Choose the region closest to your users
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        sync: false  # Will be set manually in Render dashboard
    healthCheckPath: /
    numInstances: 1

  # Frontend Service
  - type: web
    name: kuroai-frontend
    env: docker
    region: frankfurt
    rootDir: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false  # Will be set manually in Render dashboard
    numInstances: 1

databases:
  - name: kuroai-db
    region: frankfurt
    plan: free  # Adjust based on needs
